import { 
  UserProfile, 
  Transaction, 
  AuditClaim, 
  ContributionRule, 
  MemberTreatEvent, 
  VenuePlace, 
  PlannedActivity 
} from '@/types/trf';

export const INITIAL_MEMBERS: UserProfile[] = [
  {
    id: 'user-1',
    employeeId: 'TL-1001',
    name: 'Asim Khan',
    email: 'asim.manager@company.com',
    role: 'manager',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    department: 'Engineering',
    designation: 'Engineering Lead & TRF Custodian',
    joiningDate: '2023-01-15',
    birthDate: '1995-10-18', // coming up soon!
    joiningFeeStatus: 'paid',
    joiningFeeAmount: 1000,
    phone: '+92 300 1234567',
    isActive: true,
  },
  {
    id: 'user-2',
    employeeId: 'TL-1008',
    name: 'Zainab Malik',
    email: 'zainab.m@company.com',
    role: 'member',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    department: 'Engineering',
    designation: 'Senior Frontend Engineer',
    joiningDate: '2023-06-01',
    birthDate: '1996-10-12', // Very close! (in 3 days)
    joiningFeeStatus: 'paid',
    joiningFeeAmount: 1000,
    phone: '+92 321 9876543',
    isActive: true,
  },
  {
    id: 'user-3',
    employeeId: 'TL-1014',
    name: 'Bilal Ahmed',
    email: 'bilal.ahmed@company.com',
    role: 'member',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    department: 'Engineering',
    designation: 'Backend Developer',
    joiningDate: '2024-02-10',
    birthDate: '1998-11-05',
    joiningFeeStatus: 'paid',
    joiningFeeAmount: 1000,
    phone: '+92 333 5551234',
    isActive: true,
  },
  {
    id: 'user-4',
    employeeId: 'TL-1021',
    name: 'Hamza Tariq',
    email: 'hamza.t@company.com',
    role: 'member',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    department: 'Engineering',
    designation: 'Full Stack Engineer',
    joiningDate: '2024-04-15',
    birthDate: '1997-11-24',
    joiningFeeStatus: 'paid',
    joiningFeeAmount: 1000,
    phone: '+92 345 6789012',
    isActive: true,
  },
  {
    id: 'user-5',
    employeeId: 'TL-1025',
    name: 'Fatima Noor',
    email: 'fatima.noor@company.com',
    role: 'member',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    department: 'UI/UX',
    designation: 'Product Designer',
    joiningDate: '2024-05-20',
    birthDate: '1999-12-04',
    joiningFeeStatus: 'paid',
    joiningFeeAmount: 1000,
    phone: '+92 312 3456789',
    isActive: true,
  },
  {
    id: 'user-6',
    employeeId: 'TL-1030',
    name: 'Usman Ali',
    email: 'usman.ali@company.com',
    role: 'member',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    department: 'QA & Testing',
    designation: 'QA Automation Engineer',
    joiningDate: '2024-07-01',
    birthDate: '1996-01-19',
    joiningFeeStatus: 'paid',
    joiningFeeAmount: 1000,
    phone: '+92 301 2345678',
    isActive: true,
  },
  {
    id: 'user-7',
    employeeId: 'TL-1037',
    name: 'Ayesha Siddiqui',
    email: 'ayesha.s@company.com',
    role: 'member',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    department: 'Engineering',
    designation: 'DevOps / Cloud Specialist',
    joiningDate: '2024-08-15',
    birthDate: '1997-03-22',
    joiningFeeStatus: 'paid',
    joiningFeeAmount: 1000,
    phone: '+92 315 8765432',
    isActive: true,
  },
  {
    id: 'user-8',
    employeeId: 'TL-1042',
    name: 'Mustafa Raza',
    email: 'mustafa.r@company.com',
    role: 'member',
    avatarUrl: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=150&auto=format&fit=crop&q=80',
    department: 'Engineering',
    designation: 'Associate Software Engineer',
    joiningDate: '2026-09-28', // New member!
    birthDate: '2001-05-14',
    joiningFeeStatus: 'pending', // Joining fee due!
    joiningFeeAmount: 1000,
    phone: '+92 334 9876543',
    isActive: true,
  },
];

export const INITIAL_CLAIMS: AuditClaim[] = [
  {
    id: 'claim-07-26',
    monthYear: 'July 2026',
    headcount: 7,
    ratePerHead: 1400,
    totalAmount: 9800,
    status: 'approved_disbursed',
    submissionDate: '2026-07-05',
    disbursedDate: '2026-07-15',
    claimRefNumber: 'TRF-AUD-2026-07',
    auditNotes: 'Verified with HR active headcount sheet. Disbursed via Finance transfer.',
    submittedBy: 'Asim Khan',
  },
  {
    id: 'claim-08-26',
    monthYear: 'August 2026',
    headcount: 7,
    ratePerHead: 1400,
    totalAmount: 9800,
    status: 'approved_disbursed',
    submissionDate: '2026-08-04',
    disbursedDate: '2026-08-14',
    claimRefNumber: 'TRF-AUD-2026-08',
    auditNotes: 'Approved by Audit Team without remarks.',
    submittedBy: 'Asim Khan',
  },
  {
    id: 'claim-09-26',
    monthYear: 'September 2026',
    headcount: 8,
    ratePerHead: 1400,
    totalAmount: 11200,
    status: 'approved_disbursed',
    submissionDate: '2026-09-03',
    disbursedDate: '2026-09-18',
    claimRefNumber: 'TRF-AUD-2026-09',
    auditNotes: 'Headcount updated to 8 following Mustafa Raza joining.',
    submittedBy: 'Asim Khan',
  },
  {
    id: 'claim-10-26',
    monthYear: 'October 2026',
    headcount: 8,
    ratePerHead: 1400,
    totalAmount: 11200,
    status: 'submitted', // Current active claim awaiting audit!
    submissionDate: '2026-10-04',
    claimRefNumber: 'TRF-AUD-2026-10',
    auditNotes: 'Claim form submitted to Internal Audit Dept. Pending disbursement approval.',
    submittedBy: 'Asim Khan',
  },
];

export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: 'tx-001',
    date: '2026-07-15',
    title: 'Company TRF Allowance - July 2026',
    description: '7 team members @ 1,400 PKR per head disbursed by company audit',
    amount: 9800,
    type: 'inflow',
    category: 'company_claim',
    loggedBy: 'Asim Khan',
    createdAt: '2026-07-15T11:00:00Z',
  },
  {
    id: 'tx-002',
    date: '2026-07-28',
    title: 'Team Bowling Night & Snacks',
    description: 'Bowling alley session at Centaurus Megaplex + cold drinks',
    amount: 6200,
    type: 'outflow',
    category: 'activity_outing',
    loggedBy: 'Asim Khan',
    createdAt: '2026-07-28T19:30:00Z',
  },
  {
    id: 'tx-003',
    date: '2026-08-14',
    title: 'Company TRF Allowance - August 2026',
    description: '7 team members @ 1,400 PKR per head disbursed by company audit',
    amount: 9800,
    type: 'inflow',
    category: 'company_claim',
    loggedBy: 'Asim Khan',
    createdAt: '2026-08-14T10:00:00Z',
  },
  {
    id: 'tx-004',
    date: '2026-08-16',
    title: 'Ayesha Siddiqui - Joining Fee Contribution',
    description: 'Mandatory initial TRF pool joining contribution',
    amount: 1000,
    type: 'inflow',
    category: 'joining_fee',
    loggedBy: 'Asim Khan',
    relatedMemberId: 'user-7',
    createdAt: '2026-08-16T12:00:00Z',
  },
  {
    id: 'tx-005',
    date: '2026-08-20',
    title: 'Independence Day Hi-Tea & Celebration',
    description: 'Samosas, jalebi, patties and chai from Tehzeeb Bakers',
    amount: 4500,
    type: 'outflow',
    category: 'snacks_refreshment',
    loggedBy: 'Asim Khan',
    createdAt: '2026-08-20T16:00:00Z',
  },
  {
    id: 'tx-006',
    date: '2026-09-05',
    title: 'New Phone Treat - Bilal Ahmed (iPhone 16 Pro)',
    description: 'Bilal contributed treat share for purchasing new iPhone',
    amount: 3500,
    type: 'inflow',
    category: 'treat_event',
    loggedBy: 'Bilal Ahmed',
    relatedMemberId: 'user-3',
    createdAt: '2026-09-05T14:30:00Z',
  },
  {
    id: 'tx-007',
    date: '2026-09-18',
    title: 'Company TRF Allowance - September 2026',
    description: '8 team members @ 1,400 PKR per head disbursed by company audit',
    amount: 11200,
    type: 'inflow',
    category: 'company_claim',
    loggedBy: 'Asim Khan',
    createdAt: '2026-09-18T10:15:00Z',
  },
  {
    id: 'tx-008',
    date: '2026-09-22',
    title: 'Team Barbecue Dinner at Ranchers F-7',
    description: 'Burgers, loaded fries and shakes for whole sprint milestone celebration',
    amount: 8900,
    type: 'outflow',
    category: 'team_dinner',
    loggedBy: 'Asim Khan',
    createdAt: '2026-09-22T20:45:00Z',
  },
  {
    id: 'tx-009',
    date: '2026-10-02',
    title: 'Certification Treat - Zainab Malik',
    description: 'AWS Solutions Architect Professional certification celebration contribution',
    amount: 3000,
    type: 'inflow',
    category: 'treat_event',
    loggedBy: 'Zainab Malik',
    relatedMemberId: 'user-2',
    createdAt: '2026-10-02T11:00:00Z',
  },
];

export const INITIAL_RULES: ContributionRule[] = [
  // --- OFFICIAL (22 Rules) ---
  {
    id: 'rule-off-1',
    title: 'Official: New Techlogix Joining',
    description: 'New Techlogix Joining',
    suggestedAmount: 4000,
    icon: 'UserPlus',
    isMandatory: true,
    category: 'official',
  },
  {
    id: 'rule-off-2',
    title: 'Official: Team/TRF Joining',
    description: 'Team/TRF joining contribution',
    suggestedAmount: 2000,
    icon: 'Users',
    isMandatory: true,
    category: 'official',
  },
  {
    id: 'rule-off-3',
    title: 'Official: Hardware Upgrade',
    description: 'Hardware Upgrade',
    suggestedAmount: 500,
    icon: 'Cpu',
    isMandatory: false,
    category: 'official',
  },
  {
    id: 'rule-off-4',
    title: 'Official: Laptop',
    description: 'Official Laptop allocation/upgrade',
    suggestedAmount: 1000,
    icon: 'Laptop',
    isMandatory: false,
    category: 'official',
  },
  {
    id: 'rule-off-5',
    title: 'Official: Employee of the Month (EOM)',
    description: 'Employee of the Month (EOM) celebration',
    suggestedAmount: 1000,
    icon: 'Award',
    isMandatory: false,
    category: 'official',
  },
  {
    id: 'rule-off-6',
    title: 'Official: Bike',
    description: 'Official Bike conveyance',
    suggestedAmount: 1000,
    icon: 'Bike',
    isMandatory: false,
    category: 'official',
  },
  {
    id: 'rule-off-7',
    title: 'Official: Car - Hatch Back',
    description: 'Official Car - Hatch Back',
    suggestedAmount: 2000,
    icon: 'Car',
    isMandatory: false,
    category: 'official',
  },
  {
    id: 'rule-off-8',
    title: 'Official: Car - Sedan',
    description: 'Official Car - Sedan',
    suggestedAmount: 3000,
    icon: 'Car',
    isMandatory: false,
    category: 'official',
  },
  {
    id: 'rule-off-9',
    title: 'Official: Promotion - Senior Engineer',
    description: 'Promotion to Senior Engineer',
    suggestedAmount: 1000,
    icon: 'TrendingUp',
    isMandatory: false,
    category: 'official',
  },
  {
    id: 'rule-off-10',
    title: 'Official: Promotion - Principal Engineer',
    description: 'Promotion to Principal Engineer',
    suggestedAmount: 1500,
    icon: 'TrendingUp',
    isMandatory: false,
    category: 'official',
  },
  {
    id: 'rule-off-11',
    title: 'Official: Promotion - Manager',
    description: 'Promotion to Manager',
    suggestedAmount: 2000,
    icon: 'Briefcase',
    isMandatory: false,
    category: 'official',
  },
  {
    id: 'rule-off-12',
    title: 'Official: Promotion - Senior Manager',
    description: 'Promotion to Senior Manager',
    suggestedAmount: 3000,
    icon: 'Briefcase',
    isMandatory: false,
    category: 'official',
  },
  {
    id: 'rule-off-13',
    title: 'Official: Increment - Contractual to Permanent',
    description: 'Contractual to Permanent transition',
    suggestedAmount: 2000,
    icon: 'CheckCircle2',
    isMandatory: false,
    category: 'official',
  },
  {
    id: 'rule-off-14',
    title: 'Official: Increment - SE, SSE, PSE',
    description: 'Annual increment for SE, SSE, PSE',
    suggestedAmount: 2000,
    icon: 'TrendingUp',
    isMandatory: false,
    category: 'official',
  },
  {
    id: 'rule-off-15',
    title: 'Official: Increment - Mgr, Senior Mgr.',
    description: 'Annual increment for Mgr, Senior Mgr.',
    suggestedAmount: 3000,
    icon: 'Briefcase',
    isMandatory: false,
    category: 'official',
  },
  {
    id: 'rule-off-16',
    title: 'Official: Variable Compensation',
    description: 'Variable Compensation disbursement',
    suggestedAmount: 3000,
    icon: 'DollarSign',
    isMandatory: false,
    category: 'official',
  },
  {
    id: 'rule-off-17',
    title: 'Official: Missed Scrum Logs for 2 Days Con',
    description: 'Missed Scrum Logs for 2 Consecutive Days',
    suggestedAmount: 200,
    icon: 'AlertCircle',
    isMandatory: true,
    category: 'official',
  },
  {
    id: 'rule-off-18',
    title: 'Official: Missed Scrum',
    description: 'Missed Scrum meeting',
    suggestedAmount: 100,
    icon: 'AlertCircle',
    isMandatory: true,
    category: 'official',
  },
  {
    id: 'rule-off-19',
    title: 'Official: Missing DB Script UAT',
    description: 'Missing DB Script in UAT environment',
    suggestedAmount: 100,
    icon: 'Database',
    isMandatory: true,
    category: 'official',
  },
  {
    id: 'rule-off-20',
    title: 'Official: Configs/Missing Commit/DB Script Prod',
    description: 'Configs/Missing Commit/DB Script in Prod',
    suggestedAmount: 500,
    icon: 'AlertTriangle',
    isMandatory: true,
    category: 'official',
  },
  {
    id: 'rule-off-21',
    title: 'Official: Lost/Found',
    description: 'Lost/Found item fine',
    suggestedAmount: 200,
    icon: 'HelpCircle',
    isMandatory: true,
    category: 'official',
  },
  {
    id: 'rule-off-22',
    title: 'Official: International Visa',
    description: 'Official International Visa grant',
    suggestedAmount: 2000,
    icon: 'Plane',
    isMandatory: false,
    category: 'official',
  },

  // --- PERSONAL (13 Rules) ---
  {
    id: 'rule-per-1',
    title: 'Personal: Engagement',
    description: 'Engagement celebration treat',
    suggestedAmount: 1500,
    icon: 'Heart',
    isMandatory: false,
    category: 'personal',
  },
  {
    id: 'rule-per-2',
    title: 'Personal: New Property/Plot',
    description: 'New Property/Plot purchase celebration',
    suggestedAmount: 3000,
    icon: 'Home',
    isMandatory: false,
    category: 'personal',
  },
  {
    id: 'rule-per-3',
    title: 'Personal: Wedding',
    description: 'Wedding / Shaadi celebration treat',
    suggestedAmount: 2000,
    icon: 'Heart',
    isMandatory: false,
    category: 'personal',
  },
  {
    id: 'rule-per-4',
    title: 'Personal: New Born Baby',
    description: 'New Born Baby celebration treat',
    suggestedAmount: 2000,
    icon: 'Smile',
    isMandatory: false,
    category: 'personal',
  },
  {
    id: 'rule-per-5',
    title: 'Personal: Bike',
    description: 'Personal Bike purchase treat',
    suggestedAmount: 1000,
    icon: 'Bike',
    isMandatory: false,
    category: 'personal',
  },
  {
    id: 'rule-per-6',
    title: 'Personal: Car',
    description: 'Personal Car purchase treat',
    suggestedAmount: 3000,
    icon: 'Car',
    isMandatory: false,
    category: 'personal',
  },
  {
    id: 'rule-per-7',
    title: 'Personal: Laptop',
    description: 'Personal Laptop purchase treat',
    suggestedAmount: 1500,
    icon: 'Laptop',
    isMandatory: false,
    category: 'personal',
  },
  {
    id: 'rule-per-8',
    title: 'Personal: Degree/Convocation',
    description: 'Degree/Convocation milestone treat',
    suggestedAmount: 1000,
    icon: 'GraduationCap',
    isMandatory: false,
    category: 'personal',
  },
  {
    id: 'rule-per-9',
    title: 'Personal: Mobile (<= 100,000)',
    description: 'Mobile purchase <= 100,000 PKR',
    suggestedAmount: 500,
    icon: 'Smartphone',
    isMandatory: false,
    category: 'personal',
  },
  {
    id: 'rule-per-10',
    title: 'Personal: Mobile (> 100,000)',
    description: 'Mobile purchase > 100,000 PKR',
    suggestedAmount: 1000,
    icon: 'Smartphone',
    isMandatory: false,
    category: 'personal',
  },
  {
    id: 'rule-per-11',
    title: 'Personal: Medal - Gold',
    description: 'Gold Medal achievement treat',
    suggestedAmount: 2000,
    icon: 'Award',
    isMandatory: false,
    category: 'personal',
  },
  {
    id: 'rule-per-12',
    title: 'Personal: Medal - Silver',
    description: 'Silver Medal achievement treat',
    suggestedAmount: 1000,
    icon: 'Award',
    isMandatory: false,
    category: 'personal',
  },
  {
    id: 'rule-per-13',
    title: 'Personal: Medal - Bronze',
    description: 'Bronze Medal achievement treat',
    suggestedAmount: 500,
    icon: 'Award',
    isMandatory: false,
    category: 'personal',
  },
];

export const INITIAL_TREAT_EVENTS: MemberTreatEvent[] = [
  {
    id: 'treat-1',
    memberId: 'user-3',
    memberName: 'Bilal Ahmed',
    ruleTitle: 'New Smartphone / Laptop Treat',
    details: 'Bought iPhone 16 Pro Max 256GB Desert Titanium',
    amount: 3500,
    date: '2026-09-05',
    status: 'collected',
    collectedDate: '2026-09-05',
  },
  {
    id: 'treat-2',
    memberId: 'user-2',
    memberName: 'Zainab Malik',
    ruleTitle: 'Professional Certification Pass',
    details: 'Passed AWS Certified Solutions Architect - Professional exam with 890 score!',
    amount: 3000,
    date: '2026-10-02',
    status: 'collected',
    collectedDate: '2026-10-02',
  },
  {
    id: 'treat-3',
    memberId: 'user-4',
    memberName: 'Hamza Tariq',
    ruleTitle: 'New Smartphone / Laptop Treat',
    details: 'Upgraded to M3 MacBook Air 15-inch',
    amount: 3000,
    date: '2026-10-07',
    status: 'pending', // Pending collection!
  },
  {
    id: 'treat-4',
    memberId: 'user-8',
    memberName: 'Mustafa Raza',
    ruleTitle: 'New Member Joining Fee',
    details: 'Joining TRF team pool entry contribution',
    amount: 1000,
    date: '2026-09-28',
    status: 'pending', // Pending collection!
  },
];

export const INITIAL_VENUES: VenuePlace[] = [
  {
    id: 'venue-1',
    name: 'Monal Restaurant & Terrace',
    category: 'restaurant',
    location: 'Pir Sohawa Road, Margalla Hills, Islamabad',
    estimatedCostPerHead: 2800,
    rating: 4.8,
    votes: ['user-1', 'user-2', 'user-4', 'user-5', 'user-7'],
    suggestedBy: 'Asim Khan',
    description: 'Iconic mountain-top dining with panoramic view of the twin cities. Great mix of BBQ & desi cuisines.',
    mapsUrl: 'https://maps.google.com',
    status: 'wishlist',
  },
  {
    id: 'venue-2',
    name: 'Super Space Gaming Arcade',
    category: 'gaming',
    location: 'Giga Mall / Centaurus',
    estimatedCostPerHead: 1500,
    rating: 4.6,
    votes: ['user-3', 'user-4', 'user-6', 'user-8'],
    suggestedBy: 'Bilal Ahmed',
    description: 'VR gaming, bumper cars, simulator racing, and laser tag arena for team bonding.',
    mapsUrl: 'https://maps.google.com',
    status: 'wishlist',
  },
  {
    id: 'venue-3',
    name: 'Roasters Coffee House & Grill',
    category: 'cafe',
    location: 'Beverly Centre, Blue Area, Islamabad',
    estimatedCostPerHead: 2200,
    rating: 4.5,
    votes: ['user-2', 'user-5', 'user-7'],
    suggestedBy: 'Fatima Noor',
    description: 'Classic gourmet steaks, skillet cookies, pasta and artisan hot/cold coffees.',
    mapsUrl: 'https://maps.google.com',
    status: 'planned',
  },
  {
    id: 'venue-4',
    name: 'Megazone Bowling & Snooker Arena',
    category: 'adventure',
    location: 'F-9 Fatima Jinnah Park, Islamabad',
    estimatedCostPerHead: 1200,
    rating: 4.4,
    votes: ['user-1', 'user-3', 'user-6'],
    suggestedBy: 'Usman Ali',
    description: 'Full-sized bowling lanes inside scenic F-9 Park with casual cafe seating.',
    status: 'visited',
  },
  {
    id: 'venue-5',
    name: 'The Smokey Cauldron (Theme Cafe)',
    category: 'cafe',
    location: 'F-6 Super Market, Islamabad',
    estimatedCostPerHead: 1800,
    rating: 4.7,
    votes: ['user-2', 'user-4', 'user-5'],
    suggestedBy: 'Zainab Malik',
    description: 'Harry Potter themed magic cafe with butterbeer, burgers, and fantasy ambiance.',
    status: 'wishlist',
  },
];

export const INITIAL_PLANNED_ACTIVITIES: PlannedActivity[] = [
  {
    id: 'act-1',
    title: 'October Sprint Chill & Dinner at Roasters',
    venueId: 'venue-3',
    venueName: 'Roasters Coffee House & Grill',
    date: '2026-10-23',
    time: '7:30 PM',
    estimatedTotalBudget: 17600,
    trfContributionShare: 12000,
    personalContributionPerHead: 700,
    status: 'confirmed',
    description: 'Celebration of Q3 releases and welcoming Mustafa to the engineering team.',
    rsvps: [
      { userId: 'user-1', userName: 'Asim Khan', status: 'going' },
      { userId: 'user-2', userName: 'Zainab Malik', status: 'going' },
      { userId: 'user-3', userName: 'Bilal Ahmed', status: 'going' },
      { userId: 'user-4', userName: 'Hamza Tariq', status: 'going' },
      { userId: 'user-5', userName: 'Fatima Noor', status: 'maybe' },
      { userId: 'user-6', userName: 'Usman Ali', status: 'going' },
      { userId: 'user-7', userName: 'Ayesha Siddiqui', status: 'going' },
      { userId: 'user-8', userName: 'Mustafa Raza', status: 'going' },
    ],
  },
];
